config/routes.rb
Findyourgig::Application.routes.draw do

  scope '(:locale)', locale: /en|fr/ do

    devise_for :users, path: "profile", path_names: { 
                                                  sign_in: 'login', 
                                                  sign_out: 'logout',
                                                  registration: 'register' }

    authenticated :user do
      root to: 'home#index'
    end

    resources :users, path: "profile", only: [:show, :edit, :update]

    resources :bands do
      put "request_participation", on: :member
      get "members", on: :member

      resources :band_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
    end

    resources :band_participations, path: "my_bands", only: [:index, :destroy] do
      put 'set_administration_rights', on: :member
      put 'activate', on: :member
    end

    resources :managerships, path: "my_venues", only: [:index]

    resources :venues do
      get "gigs", on: :member
      resources :venue_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
      resources :feedbacks do
        resources :feedback_ratings
        resources :feedback_comments
      end
    end

    resources :gigs do
      get "poster", on: :member
      put "remove_poster", on: :member
    end

    match '/search', :to => 'home#search'

    root to: "home#index"
  end  
end

app/models/band_participation.rb
class BandParticipation < ActiveRecord::Base
  scope :active, where(pending: false)

  belongs_to :user
  belongs_to :band

  attr_accessible :band_id, :date_joined, :is_admin, :user_id

  validates_presence_of :band_id, :user_id, :date_joined
  validates_uniqueness_of :band_id, scope: :user_id
  validate :user_has_role_band_member

  def user_has_role_band_member
    return if user.nil?
    errors[:base] << "User is not a band member and cannot be included in this band" unless user.has_role? :band_member
  end
end

app/controllers/band_participations_controller.rb
class BandParticipationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user_must_be_band_member, only: [:index]
  before_filter :find_band_participation, only: [:destroy, :set_administration_rights, :activate]
  before_filter :only_member_admin, only: [:set_administration_rights, :activate]
  respond_to :html

  def index
    @participations = current_user.band_participations.active.order("date_joined DESC").includes(:band => :main_image)
  end

  def set_administration_rights
    @bp.update_attribute(:is_admin, !@bp.is_admin)
    is_admin_notice = @bp.is_admin ? 'user_rights_is_admin' : 'user_rights_not_admin'
    redirect_to members_band_path(@bp.band), notice: t(is_admin_notice, user: @bp.user.name).html_safe
  end

  def activate
    if @bp.pending
      @bp.update_attribute(:pending, false)
      redirect_to members_band_path(@bp.band), notice: t('member_activated', :user => @bp.user.name)
    else
      redirect_to members_band_path(@bp.band), notice: t('member_already_activated', :user => @bp.user.name)
    end
  end

  def destroy
    if @bp.user_id == current_user.id
      @bp.destroy
      redirect_to band_participations_path, notice: t('band_participation_removed', band: @bp.band.name)
    else
      redirect_to root_path, alert: t('unprocessable_action')
    end
  end

  private
  def find_band_participation
    @bp = BandParticipation.find_by_id(params[:id])
    redirect_to root_path, alert: t('band_participation_unknown') if @bp.nil?
  end

  def only_member_admin
    unless current_user.band_participations.detect { |part| part.band_id == @bp.band_id && part.is_admin }
      redirect_to bands_path, alert: t('page_unknown')
    end
  end

  def user_must_be_band_member
    redirect_to root_path, alert: t('page_unknown') unless current_user.is_band_member?
  end
end

app/helpers/band_participations_helper.rb
module BandParticipationsHelper
end

app/views/band_participations/_sidebar.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-list">
    <li class="nav-header"><%= t('menu') %></li>
    <li><%= link_to t('menu_bands'), bands_path %></li>
    <% if user_signed_in? && current_user.roles_list.include?(User::BAND_MEMBER) %>
      <li><%= link_to t('menu_my_bands'), band_participations_path %></li>
    <% end %>
    <li><%= link_to t('menu_venues'), venues_path %></li>
  </ul>
<% end %>

app/views/band_participations/index.html.erb
<h2><%= t('menu_my_bands') %></h2>

<% if @participations.any? %>
  <table class="table table-bordered table-striped">

  <% @participations.each do |participation| %>
  <tr>
    <td class="element-cell">
      <% if participation.band.main_image && participation.band.main_image.file? %>
        <%= image_tag participation.band.main_image.file_url(:thumb), class: "pull-left" %>
      <% else %>
        <%= image_tag "no-image.png", class: "pull-left" %>
      <% end %>

      <h4><%= link_to participation.band.name, participation.band %></h4>
      <%= participation.band.creation_year %><br />
      <%= participation.band.city %><br />
      <br />
      <%= t('.date_join') %> <strong><%= l(participation.date_joined) %></strong><br />
      <strong><%= pluralize(participation.band.band_participations.count, t('.member')) %></strong>

      <%= link_to t('.leave_band'), band_participation_path(participation), method: :delete, confirm: t('are_u_sure'), class: "btn btn-small btn-warning pull-right" %>
      <% if participation.is_admin %>
        <%= link_to t('remove'), participation.band, method: :delete, data: { confirm: t('are_u_sure') }, class: "btn btn-small btn-danger pull-right" %>
        <%= link_to t('edit'), edit_band_path(participation.band), class: "btn btn-small btn-success pull-right" %>
        <%= link_to t('.members'), members_band_path(participation.band), class: "btn btn-small pull-right" %>
      <% end %>
      <%= link_to t('.see_band_page'), participation.band, class: "btn btn-small btn-info pull-right" %>
    </td>    
  </tr>
  <% end %>

  </table>
<% else %>
  <div class="alert alert-info"><%= t('no_result') %></div>
<% end %>

<%= render 'shared/sidebar' %>