config/routes.rb
Findyourgig::Application.routes.draw do

  scope '(:locale)', locale: /en|fr/ do

    devise_for :users, path: "profile", path_names: { 
                                                  sign_in: 'login', 
                                                  sign_out: 'logout',
                                                  registration: 'register' }

    authenticated :user do
      root to: 'home#index'
    end

    resources :users, path: "profile", only: [:show, :edit, :update]

    resources :bands do
      put "request_participation", on: :member
      get "members", on: :member

      resources :band_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
    end

    resources :band_participations, path: "my_bands", only: [:index, :destroy] do
      put 'set_administration_rights', on: :member
      put 'activate', on: :member
    end

    resources :managerships, path: "my_venues", only: [:index]

    resources :venues do
      get "gigs", on: :member
      resources :venue_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
      resources :feedbacks do
        resources :feedback_ratings
        resources :feedback_comments
      end
    end

    resources :gigs do
      get "poster", on: :member
      put "remove_poster", on: :member
    end

    match '/search', :to => 'home#search'

    root to: "home#index"
  end  
end

app/views/shared/_geolocation_form.html.erb
<div class="geolocation">
  <%= form_tag search_path, method: :get do %>
    <div class="geolocation-alerts"></div>
    <%= hidden_field_tag :latitude, params[:latitude] %>
    <%= hidden_field_tag :longitude, params[:longitude] %>
    <%= label_tag :formatted_address, t('.type_address_or_zipcode') %>
    <%= text_field_tag :formatted_address, params[:formatted_address], class: "span12" %><br />
    <%= submit_tag t('.closest_venues_button'), name: "find_venues", class: "btn btn-large btn-primary span6" %>
    <%= submit_tag t('.closest_gigs_button'), name: "find_gigs", class: "btn btn-large span6 pull-right" %>

    <div class="clearfix"></div>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-list">
    <li class="nav-header"><%= t('menu') %></li>
    <li><%= link_to t('menu_bands'), bands_path %></li>
    <% if user_signed_in? && current_user.roles_list.include?(User::BAND_MEMBER) %>
      <li><%= link_to t('menu_my_bands'), band_participations_path %></li>
    <% end %>
    <li><%= link_to t('menu_venues'), venues_path %></li>

    <% if user_signed_in? && current_user.roles_list.include?(User::VENUE_MANAGER) %>
      <li><%= link_to t('menu_my_venues'), managerships_path %></li>
    <% end %>
    <li><%= link_to t('menu_gigs'), gigs_path %></li>
  </ul>
<% end %>