config/routes.rb
Findyourgig::Application.routes.draw do

  scope '(:locale)', locale: /en|fr/ do

    devise_for :users, path: "profile", path_names: { 
                                                  sign_in: 'login', 
                                                  sign_out: 'logout',
                                                  registration: 'register' }

    authenticated :user do
      root to: 'home#index'
    end

    resources :users, path: "profile", only: [:show, :edit, :update]

    resources :bands do
      put "request_participation", on: :member
      get "members", on: :member

      resources :band_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
    end

    resources :band_participations, path: "my_bands", only: [:index, :destroy] do
      put 'set_administration_rights', on: :member
      put 'activate', on: :member
    end

    resources :managerships, path: "my_venues", only: [:index]

    resources :venues do
      get "gigs", on: :member
      resources :venue_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
      resources :feedbacks do
        resources :feedback_ratings
        resources :feedback_comments
      end
    end

    resources :gigs do
      get "poster", on: :member
      put "remove_poster", on: :member
    end

    match '/search', :to => 'home#search'

    root to: "home#index"
  end  
end

app/models/band.rb
class Band < ActiveRecord::Base
  default_scope order('created_at DESC')
  scope :by_letter, lambda { |letter| { :conditions => ["lower(name) LIKE ?", "#{letter}%"] }}

  has_many :band_participations, dependent: :destroy
  has_many :users, through: :band_participations
  has_many :band_images, dependent: :destroy
  has_many :acts, dependent: :destroy
  has_many :gigs, through: :acts

  has_one :main_image, class_name: BandImage, conditions: { is_main: true }

  attr_accessible :city, :creation_year, :description, :name

  validates_presence_of :name, :creation_year

  after_destroy :remove_upload_folder

  def remove_upload_folder
    FileUtils.remove_dir("#{Rails.root}/public/uploads/bands/#{self.id}", :force => true)
  end

  def in_band_participations?(participations)
     participations.detect { |member| member.band_id == self.id }
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_band, only: [:show, :edit, :update, :destroy, :request_participation, :members]
  before_filter :find_user_bands, only: [:index, :show, :request_participation, :edit, :update, :destroy, :members]
  before_filter :only_member_admin, only: [:edit, :update, :destroy, :members]
  before_filter :only_band_member, only: [:new, :create]
  respond_to :html

  def index
    if params[:search]
      search = Regexp.escape params[:search]
      @bands = Band.all({:conditions => ["lower(name) LIKE ?", "%#{search.downcase}%"], include: :main_image})
    elsif params[:by_letter]
      @bands = Band.includes(:main_image).by_letter(params[:by_letter].downcase)
    else
      @bands = Band.includes(:main_image).limit(10)
    end
    respond_with @bands
  end

  def show
    flash.now[:info] = t('band_participation_request_pending') if @user_bands.detect { |part| part[:band_id] == @band.id && part[:active] == false }
    @gigs = @band.gigs.upcoming
    @nb_images = @band.band_images.count
    @band_images = @band.band_images.limit(4)
    @main_image = @band.main_image
    @members = @band.users
    respond_with @band
  end

  def new
    @band = Band.new
    respond_with @band
  end

  def edit
  end

  def create
    @band = Band.new(params[:band])

    if @band.save
      @band.band_participations.create user_id: current_user.id, is_admin: true, date_joined: Date.today do |p|
        p.pending = false
      end
      redirect_to @band, notice: t('band_created')
    else
      render action: "new"
    end
  end

  def update
    if @band.update_attributes(params[:band])
      redirect_to @band, notice: t('band_updated')
    else
      render action: "edit"
    end
  end

  def request_participation
    unless @user_bands.collect { |part| part[:band_id] }.include? @band.id
      @participation = current_user.band_participations.build band_id: @band.id, is_admin: false, date_joined: Date.today
      if @participation.save
        redirect_to @band, notice: t('band_participation_request_sent')
      else
        redirect_to @band, alert: t('band_participation_request_could_not_be_sent')
      end
    else
      redirect_to band_participations_path, alert: t('already_participates')
    end
  end

  def members
    @members = @band.band_participations.order("date_joined ASC")
  end

  def destroy
    @band.destroy
    redirect_to bands_url
  end

  private
  def find_band
    begin
      @band = Band.find(params[:id])
    rescue
      redirect_to bands_url, alert: t('band_unknown')
    end
  end

  def find_user_bands
    @user_bands = []
    @user_bands = current_user.band_participations.collect { |p| { band_id: p.band_id, admin: p.is_admin, active: !p.pending } } if current_user
  end

  def only_member_admin
    unless user_signed_in? && @user_bands.detect { |part| part[:band_id] == @band.id && part[:admin] == true }
      redirect_to bands_path, alert: t('page_unknown')
    end
  end

  def only_band_member
    redirect_to bands_path, alert: t('page_unknown') unless current_user.roles_list.include?(User::BAND_MEMBER)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :required => "required" %>
  </p>
  <p>
    <%= f.label :creation_year %>
    <%= f.number_field :creation_year, class: "input-small", :required => "required" %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, class: "span8", rows: "8" %>
  </p>
  <p><%= f.submit class: "btn btn-primary" %></p>
<% end %>

app/views/bands/edit.html.erb
<h2 class="page-header"><%= @band.name %> <%= link_to t('.band_page'), @band, class: "btn btn-info pull-right" %></h2>

<%= render 'form' %>
<%= render 'shared/sidebar' %>

app/views/bands/index.html.erb
<table class="table table-bordered table-striped">
  <tr>
    <% ("a".."z").to_a.each do |letter| %>
      <td class="center"><%= link_to letter.upcase, bands_path(:by_letter => letter) %></td>
    <% end %>
  </tr>
</table>

<%= link_to t('.create_band'), new_band_path, class: "btn btn-primary pull-right" if user_signed_in? && current_user.roles_list.include?(User::BAND_MEMBER) %>

<% if params[:by_letter] %>
  <h2><%= t('.bands_starting_with_letter') %> <%= params[:by_letter].upcase %></h2>
<% else %>
  <h2><%= t('.last_ten_bands') %></h2>
<% end %>

<%= form_tag({controller: "bands", action: "index"}, method: "get", class: "form-search pull-right") do %>
  <div class="input-prepend">
    <span class="add-on"><i class="icon-search"></i></span>
    <%= text_field_tag :search, params[:search], class: "search-query", :placeholder => "#{t('search')}..." %>
  </div>
  <%= submit_tag t('ok'), class: "btn" %>
<% end %>

<% if @bands.any? %>
  <table class="table table-bordered table-striped">

  <% @bands.each do |band| %>
    <tr>
      <td class="element-cell">
        <% if band.main_image && band.main_image.file? %>
          <%= link_to (image_tag band.main_image.file_url(:thumb), class: "pull-left"), band %>
        <% else %>
          <%= link_to (image_tag "no-image.png", class: "pull-left"), band %>
        <% end %>

        <h4><%= link_to band.name, band %></h4>
        <%= band.creation_year %><br />
        <%= band.city %><br />
        <% unless band.description.blank? %>
          <%= band.description %>
        <% else %>
          <em><%= t('no_description') %></em>
        <% end %><br />
        <% if user_signed_in? && @user_bands.detect { |part| part[:band_id] == band.id && part[:admin] == true } %>
          <%= link_to t('remove'), band, method: :delete, data: { confirm: t('are_u_sure') }, class: "btn btn-small btn-danger pull-right" %>
          <%= link_to t('edit'), edit_band_path(band), class: "btn btn-small btn-success pull-right" %>
        <% end %>
        <%= link_to t('.see_band_page'), band, class: "btn btn-small btn-info pull-right" %>
      </td>
    </tr>
  <% end %>
  </table>
<% else %>
  <div class="alert alert-info"><%= t('no_result') %></div>
<% end %>

<%= render 'shared/sidebar' %>

app/views/bands/members.html.erb
<h2 class="page-header">
  <%= @band.name %> <small><%= t('.members') %></small> <%= link_to t('.band_page'), @band, class: "btn btn-info pull-right" %>
</h2>

<% if @members.any? %>
  <table class="table table-bordered table-striped">

  <% @members.each do |member| %>
    <tr>
      <td class="<%= 'cell-blue' if member.user_id == current_user.id %>">
        <h4>
          <%= member.user.name %>
          <% if member.is_admin %>
            <span class="label label-warning pull-right"><%= t('admin') %></span>
          <% end %>

          <% if member.pending %>
            <span class="label pull-right"><%= t('pending') %></span>
          <% end %>
        </h4>
        <%= t('.date_join') %> <strong><%= l(member.date_joined) %></strong><br />

        <% unless member.user_id == current_user.id %>
          <% if member.pending %>
            <%= link_to t('.accept_participation'), activate_band_participation_path(member), method: :put, class: "btn btn-small btn-inverse pull-right" %>
          <% else %>
            <%= link_to member.is_admin ? t('.disabled_admin') : t('.enable_admin'), set_administration_rights_band_participation_path(member), method: :put, class: "btn btn-small pull-right" %>
          <% end %>
        <% end %>

        <span class="btn btn-small btn-info pull-right"><%= t('.profile') %></span>
      </td>
    </tr>
  <% end %>
  </table>
<% else %>
  <div class="alert alert-info"><%= t('no_result') %></div>
<% end %>

<%= render 'shared/sidebar' %>

app/views/bands/my_bands.html.erb
<h2><%= t('menu_my_bands') %></h2>

<% if @participations.any? %>
  <table class="table table-bordered table-striped">

  <% @participations.each do |participation| %>
  <tr>
    <td>
      <h4><%= link_to participation.band.name, participation.band %></h4>
      <%= participation.band.creation_year %><br />
      <%= participation.band.city %><br />
      <br />
      <%= t('.date_join') %> <strong><%= l(participation.date_joined) %></strong><br />
      <strong><%= pluralize(participation.band.band_participations.count, t('.member')) %></strong><br />
      <% if participation.is_admin %>
        <%= link_to t('edit'), edit_band_path(participation.band), class: "btn btn-small btn-success pull-right", style: "margin-right: 7px;" %>
      <% end %>
      <%= link_to t('.see_band_page'), participation.band, class: "btn btn-small btn-info pull-right", style: "margin-right: 7px;" %>
    </td>    
  </tr>
  <% end %>

  </table>
<% else %>
  <div class="alert alert-info"><%= t('no_result') %></div>
<% end %>

<%= render 'sidebar' %>

app/views/bands/new.html.erb
<h2 class="page-header"><%= t('.new_band') %></h2>

<%= render 'form' %>
<%= render 'shared/sidebar' %>

app/views/bands/show.html.erb
<h2 class="page-header">
  <%= @band.name %> 

  <% if user_signed_in? %>
    <% if @user_bands.collect { |part| part[:band_id] }.include? @band.id %>
      <% if @user_bands.detect { |part| part[:band_id] == @band.id && part[:admin] == true } %>
        <%= link_to t('remove'), @band, method: :delete, data: { confirm: t('are_u_sure') }, class: "btn btn-danger pull-right" %>
        <%= link_to t('.edit_band'), edit_band_path(@band), class: "btn btn-success pull-right" %>
      <% end %>
    <% else %>
      <%= link_to t('.join_band'), request_participation_band_path(@band), method: :put, class: "btn btn-inverse pull-right" %>
    <% end %>
  <% end %>
</h2>

<p>
  <% if @main_image && @main_image.file? %>
    <%= link_to band_band_image_path(@band, @main_image) do %>
      <img src="<%= @main_image.file_url(:header) %>" />
    <% end %>
  <% end %>
</p>

<div class="row-fluid">
  <div class="span6 well-white">
    <p>
      <%= t('.created_in') %> <strong><%= @band.creation_year %></strong><br />
      <%= t('.from') %> <strong><%= @band.city %></strong>
    </p>
    <p>
      <% unless @band.description.blank? %>
        <hr />
        <%= raw @band.description.gsub("\r\n", "<br />") %>
      <% end %>
    </p>
  </div>

  <div class="span6">
    <h4><%= t('.band_members') %></h4>
    <% if @members.any? %>
      <% @members.each do |member| %>
        <div class="venue-manager-avatar pull-left">
          <%= link_to member, class: "text-info" do %>
            <% if member.avatar? %>
              <%= image_tag member.avatar_url(:thumb) %>
            <% else %>
              <%= image_tag "no-image.png" %>
            <% end %>
            <%= member.name %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <em class="muted"><%= t('.no_member') %></em>
    <% end %>
  </div>
</div>

<hr />

<h4><%= t('.pictures') %> <small>(<%= @nb_images %>)</small></h4>

<% if @band_images.any? %>
  <p class="thumbs-container">
    <% @band_images.each do |image| %>
      <% if image.file? %>
        <%= link_to image_tag(image.file_url(:thumb)), band_band_image_path(@band, image) %>
      <% end %>
    <% end %>
  <p>
  <em><%= link_to t('.all_images'), band_band_images_path(@band), class: "pull-right" %></em>
  <div class="clearfix"></div>
<% else %>
  <div class="alert">
    <%= t('.no_pictures') %>
  </div>
  <% if user_signed_in? && @user_bands.collect { |part| part[:band_id] }.include?(@band.id) %>
    <%= link_to t('.upload_images'), band_band_images_path(@band), class: "btn btn-primary pull-right" %>
    <div class="clearfix"></div>
  <% end %>
<% end %>

<hr />

<% if @gigs.any? %>
  <h3>
    <%= t('.gigs') %>

    <% if user_signed_in? && @user_bands.collect { |part| part[:band_id] }.include?(@band.id) %>
      <%= link_to t('.add_gig'), new_gig_path(:band_id => @band.id), class: "btn btn-small pull-right" %>
    <% end %>
  </h3>
  <p class="thumbs-container">
    <% @gigs.each do |gig| %>
      <%= link_to gig do %>
        <% if gig.poster? %>
          <%= image_tag gig.poster_url(:thumb) %>
        <% else %>
          <%= image_tag "no-image.png" %>
        <% end %>
        <span class="thumb-label thumb-gig"><%= gig.name %></span>
      <% end %>
    <% end %>
  </p>
<% end %>

<%= render 'shared/sidebar' %>