config/routes.rb
Findyourgig::Application.routes.draw do

  scope '(:locale)', locale: /en|fr/ do

    devise_for :users, path: "profile", path_names: { 
                                                  sign_in: 'login', 
                                                  sign_out: 'logout',
                                                  registration: 'register' }

    authenticated :user do
      root to: 'home#index'
    end

    resources :users, path: "profile", only: [:show, :edit, :update]

    resources :bands do
      put "request_participation", on: :member
      get "members", on: :member

      resources :band_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
    end

    resources :band_participations, path: "my_bands", only: [:index, :destroy] do
      put 'set_administration_rights', on: :member
      put 'activate', on: :member
    end

    resources :managerships, path: "my_venues", only: [:index]

    resources :venues do
      get "gigs", on: :member
      resources :venue_images, path: 'images', only: [:index, :create, :show, :destroy] do
        put "set_main", on: :member
      end
      resources :feedbacks do
        resources :feedback_ratings
        resources :feedback_comments
      end
    end

    resources :gigs do
      get "poster", on: :member
      put "remove_poster", on: :member
    end

    match '/search', :to => 'home#search'

    root to: "home#index"
  end  
end

app/models/band_image.rb
require 'carrierwave/orm/activerecord'

class BandImage < ActiveRecord::Base
  default_scope order('created_at DESC')

  mount_uploader :file, BandImageUploader

  belongs_to :band

  attr_accessible :band_id, :file, :is_main, :file_cache, :remote_file_url

  validates_presence_of :band_id, :file

  before_create :set_is_main
  before_destroy :remove_file_and_folder

  def set_is_main
    self.is_main = true if self.band.band_images.count.zero?
  end

  def remove_file_and_folder
    store_dir = file.store_dir
    remove_file!
    FileUtils.remove_dir("#{Rails.root}/public/#{store_dir}", :force => true)
  end

  def previous
    self.band.band_images.where('band_images.id > ?', self.id).last
  end

  def next
    self.band.band_images.where('band_images.id < ?', self.id).first
  end
end

app/controllers/band_images_controller.rb
class BandImagesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_band
  before_filter :find_band_image, only: [:show, :set_main, :destroy]
  before_filter :find_band_participations
  before_filter :only_member, only: [:create, :destroy, :set_main]
  respond_to :html

  def index
    @band_images = @band.band_images.select { |image| image.persisted? }
    @nb_images = @band.band_images.count
    @band_image = @band.band_images.build if @participations.detect { |member| member.band_id == @band.id }
    respond_with @band_images
  end

  def show
    @previous = @band_image.previous
    @next = @band_image.next
    respond_with @band_image
  end

  def create
    @band_image = @band.band_images.build(params[:band_image])

    respond_to do |format|
      if @band_image.save
        format.html { redirect_to band_band_images_path(@band), notice: t('image_uploaded') }
      else
        format.html do
          @band_images = @band.band_images.select { |image| image.persisted? }
          @nb_images = @band.band_images.count
          render :action => "index"
        end
      end
    end
  end

  def set_main
    main_image = @band.main_image
    if @band_image.update_attribute(:is_main, true)
      main_image.update_attribute(:is_main, false) if main_image
    end
    redirect_to band_band_image_path(@band, @band_image), notice: t('image_is_main')
  end

  def destroy
    @band_image.destroy
    redirect_to band_band_images_path(@band), notice: t('image_deleted')
  end

  private
  def find_band
    begin
      @band = Band.find(params[:band_id])
    rescue
      redirect_to bands_url, alert: t('band_unknown')
    end
  end

  def find_band_image
    begin
      @band_image = @band.band_images.find(params[:id])
    rescue
      redirect_to band_band_images_path(@band), alert: t('image_unknown')
    end
  end

  def find_band_participations
    @participations = []
    @participations = current_user.band_participations if current_user
  end

  def only_member
    redirect_to bands_path, alert: t('page_unknown') unless current_user && @participations.detect { |member| member.band_id == @band.id }
  end

end

app/helpers/band_images_helper.rb
module BandImagesHelper
end

app/views/band_images/index.html.erb
<h2 class="page-header">
  <%= link_to @band.name, @band %> 
</h2>

<% if user_signed_in? && @participations.detect { |member| member.band_id == @band.id }%>
  <div class="well-white">
    <h4><%= t('.add_image') %></h4>
    <%= form_for [@band, @band_image], :html => {:multipart => true} do |f| %>
      <p>
        <%= f.text_field :remote_file_url, placeholder: t('.image_url'), class: "span6" %><br />
        <strong><%= t('or') %></strong><br />
        <%= f.file_field :file %><br />
        <%= f.hidden_field :file_cache %>
      </p>
      <%= f.submit t('.upload'), class: "btn" %>
    <% end %>
  </div>
<% end %>

<h4><%= t('.pictures') %> <small>(<%= @nb_images %>)</small></h4>

<% if @band_images.any? %>
  <p class="thumbs-container">
    <% @band_images.each do |image| %>
      <% if image.file? %>
        <%= link_to band_band_image_path(@band, image) do %>
          <img src="<%= image.file_url(:thumb) %>" class="<%= 'main' if image.is_main %>" />
        <% end %>
      <% end %>
    <% end %>
  </p>
<% else %>
  <div class="alert">
    <%= t('.no_pictures') %>
  </div>
<% end %>

<%= render 'shared/sidebar' %>

app/views/band_images/show.html.erb
<h2 class="page-header">
  <%= link_to @band.name, band_band_images_path(@band) %>

  <% if user_signed_in? && @participations.detect { |member| member.band_id == @band.id }%>
    <%= link_to t('remove'), band_band_image_path(@band, @band_image), method: :delete, data: { confirm: t('are_u_sure') }, class: "btn btn-danger pull-right" %>
    <% unless @band_image.is_main %>
      <%= link_to t('.set_as_main'), set_main_band_band_image_path(@band, @band_image), method: :put, class: "btn btn-success pull-right" %>
    <% else %>
      <small><i class="icon-check"></i> <%= t('.is_main') %></small>
    <% end %>
  <% end %>
</h2>

<p class="center thumbs-container">
  <%= image_tag(@band_image.file_url(:normal)) if @band_image.file? %>
</p>

<div class="thumbs-container">
  <%= link_to image_tag(@previous.file_url(:thumb)), band_band_image_path(@band, @previous), class: "pull-left" if @previous %>
  <%= link_to image_tag(@next.file_url(:thumb)), band_band_image_path(@band, @next), class: "pull-right" if @next %>
  <div class="clearfix"></div>
</div>

<%= render 'shared/sidebar' %>